<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_CustomRegistration
 * @author    Webkul
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<script>
    window.ajaxCheckUrl = <?= /* @noEscape */ json_encode($block->getAjaxCheckUrl()); ?>;
</script>
<script>
    require([
        'jquery',
        "mage/mage",
    ], function($) {
        var alerttext = '';
        $("#save_custom_fields").on( "click", function() {
            $.ajax(window.ajaxCheckUrl, {
                method: 'post',
                data:$('#custom_form').serialize(),
                onSuccess: function(transport) {
                }
            });
        });       
    });
</script> 
