<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_CustomRegistration
 * @author    Webkul
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<fieldset class="fieldset customfield_options">
    <legend class="legend">
        <span><?= $block->escapeHtml(__('Manage Options (values of your attribute)')) ?></span>
    </legend>
    <div id="manage-options-panel">
        <table class="admin__control-table">
            <thead>
                <tr id="attribute-options-table">
                    <th class="col-draggable"></th>
                    <th class="col-default control-table-actions-th">
                        <span><?= $block->escapeHtml(__('Is Default')) ?></span>
                    </th>
                    <?php $storelist = $block->getStores(); ?>
                    <?php foreach ($storelist as $_store): ?>
                        <th<?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID): ?>
                         class="_required"<?php endif; ?>>
                            <span><?= $block->escapeHtml(__($_store->getName())) ?></span>
                        </th>
                    <?php endforeach; ?>
                    <?php $storetotal = count($storelist) + 3; ?>
                    <th class="col-delete">&nbsp;</th>
                </tr>
            </thead>
            <tbody data-role="options-container" class="ignore-validate"></tbody>
            <tfoot>
            <tr>
                <th colspan="<?= $block->escapeHtml($storetotal) ?>" class="validation">
                    <input type="hidden" class="required-dropdown-attribute-entry"
                           name="dropdown_attribute_validation"/>
                </th>
            </tr>
            <tr>
                <th colspan="<?= $block->escapeHtml($storetotal) ?>" class="col-actions-add">
                    <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()): ?>
                        <button id="add_new_option_button" title="<?= $block->escapeHtml(__('Add Option')) ?>"
                            type="button" class="action- scalable add">
                             <span><?= $block->escapeHtml(__('Add Option')) ?></span>
                        </button>
                    <?php endif; ?>
                </th>
            </tr>
            </tfoot>
        </table>
        <input type="hidden" id="option-count-check" value="" />
    </div>
    <script id="row-template" type="text/x-magento-template">
        <tr>
            <td class="col-draggable">
                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()): ?>
                    <div data-role="draggable-handle" class="draggable-handle"
                         title="<?= $block->escapeHtml(__('Sort Option')) ?>"></div>
                <?php endif; ?>
                <input
                    data-role="order"
                    type="hidden"
                    name="option[order][<%- data.id %>]"
                    value="<%- data.sort_order %>"
                    <?php if ($block->getReadOnly() || $block->canManageOptionDefaultOnly()): ?>
                    disabled="disabled"
                    <?php endif; ?>/>
            </td>
            <td class="col-default control-table-actions-cell">
                <input
                    class="input-radio"
                    type="<%- data.intype %>"
                    name="default[]"
                    value="<%- data.id %>"
                    <%- data.checked %>
                    <?php if ($block->getReadOnly()): ?>
                    disabled="disabled"
                    <?php endif; ?>/>
            </td>
            <?php foreach ($block->getStores() as $_store): ?>
            <td class="col-<%- data.id %>">
                <input
                    name="option[value][<%- data.id %>][<?= /** @escapeNotVerified */ $_store->getId() ?>]"
                    value="<%- data.store<?= /** @escapeNotVerified */ $_store->getId() ?> %>"
                    class="input-text <?= ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID)
                        ? 'required-option _required' : '' ?>"
                    type="text"
                    <?php if ($block->getReadOnly() || $block->canManageOptionDefaultOnly()): ?>
                    disabled="disabled"
                    <?php endif;?>/>
            </td>
            <?php endforeach; ?>
            <td id="delete_button_container_<%- data.id %>" class="col-delete">
                <input type="hidden" class="delete-flag" name="option[delete][<%- data.id %>]" value="" />
                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()): ?>
                    <button id="delete_button_<%- data.id %>"
                        title="<?= $block->escapeHtml(__('Delete')) ?>" type="button"
                        class="action- scalable delete delete-option">
                        <span><?= $block->escapeHtml(__('Delete')) ?></span>
                    </button>
                <?php endif;?>
            </td>
        </tr>
    </script>
    <?php
    $values = [];
    $defaultOption = $block->getAttributeDefaultValue();
    foreach ($block->getOptionValues() as $value) {
        array_push($values, $value->getData());
    }
    ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Webkul_CustomRegistration/js/options": {
                    "attributesData": <?= /** @escapeNotVerified */ json_encode($values); ?>,
                    "isSortable":  <?= (int)(!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()) ?>,
                    "isReadOnly": <?= (int)$block->getReadOnly() ?>,
                    "defaultOption": <?= (int)$defaultOption ?>
                }
            }
        }
    </script>
</fieldset>
