<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_CustomRegistration
 * @author    Webkul
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php /** @var $customRegistrationViewModel \Webkul\CustomRegistration\ViewModel\CustomRegistration */ ?>
<?php $customRegistrationViewModel = $block->getCustomRegistrationViewModel(); ?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Info */ ?>
<?php $_order = $block->getOrder() ?>
<?php
$orderAdminDate = $block->formatDate(
    $block->getOrderAdminDate($_order->getCreatedAt()),
    \IntlDateFormatter::MEDIUM,
    true
);
$orderStoreDate = $block->formatDate(
    $_order->getCreatedAt(),
    \IntlDateFormatter::MEDIUM,
    true,
    $block->getTimezoneForStore($_order->getStore())
);
?>

<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title">
            <?= /** @escapeNotVerified */ $block->escapeHtml(__('Order & Account Information')) ?>
        </span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <?php /* Order Information */?>
            <?php if ($_order->getEmailSent()):
                $_email = $block->escapeHtml(__('The order confirmation email was sent'));
            else:
                $_email = $block->escapeHtml(__('The order confirmation email is not sent'));
            endif; ?>
            <div class="admin__page-section-item-title">
                <span class="title">
                    <?php if ($block->getNoUseOrderLink()): ?>
                        <?= /** @escapeNotVerified */ __('Order # %1', $_order->getRealOrderId()) ?>
                         (<span><?= /** @escapeNotVerified */ $_email ?></span>)
                    <?php else: ?>
                        <a href="<?= /** @escapeNotVerified */ $block->getViewUrl($_order->getId()) ?>">
                            <?= /** @escapeNotVerified */ __('Order # %1', $_order->getRealOrderId()) ?>
                        </a>
                        <span>(<?= /** @escapeNotVerified */ $_email ?>)</span>
                    <?php endif; ?>
                </span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                <tr>
                    <th><?= $block->escapeHtml(__('Order Date')) ?></th>
                    <td><?= /** @escapeNotVerified */ $orderAdminDate ?></td>
                </tr>
                <?php if ($orderAdminDate != $orderStoreDate): ?>
                    <tr>
                        <th>
                        <?= /** @escapeNotVerified */ __(
                            'Order Date (%1)',
                            $block->getTimezoneForStore($_order->getStore())
                        ) ?>
                        </th>
                        <td><?= /** @escapeNotVerified */ $orderStoreDate ?></td>
                    </tr>
                <?php endif;?>
                <tr>
                    <th><?= $block->escapeHtml(__('Order Status')) ?></th>
                    <td><span id="order_status"><?= /** @escapeNotVerified */ $_order->getStatusLabel() ?></span></td>
                </tr>
                <?php if ($block->isSingleStoreMode() == false): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Purchased From')) ?></th>
                        <td><?= /** @escapeNotVerified */ $block->getOrderStoreName() ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getRelationChildId()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Link to the New Order')) ?></th>
                        <td>
                            <a href="<?= /** @noEscape */ $block->getViewUrl($_order->getRelationChildId()) ?>">
                                <?= /** @escapeNotVerified */ $_order->getRelationChildRealId() ?>
                            </a>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getRelationParentId()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Link to the Previous Order')) ?></th>
                        <td><a href="<?= /** @noEscape */ $block->getViewUrl($_order->getRelationParentId()) ?>">
                                <?= /** @escapeNotVerified */ $_order->getRelationParentRealId() ?>
                            </a></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getRemoteIp() && $block->shouldDisplayCustomerIp()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Placed from IP')) ?></th>
                        <td><?= /** @escapeNotVerified */ $_order->getRemoteIp(); ?>
                            <?= ($_order->getXForwardedFor())
                                ? ' (' . $block->escapeHtml($_order->getXForwardedFor()) . ')'
                                : ''; ?>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getGlobalCurrencyCode() != $_order->getBaseCurrencyCode()): ?>
                    <tr>
                        <th>
                        <?= /** @escapeNotVerified */ __(
                            '%1 / %2 rate:',
                            $_order->getGlobalCurrencyCode(),
                            $_order->getBaseCurrencyCode()
                        ) ?>
                        </th>
                        <td><?= /** @escapeNotVerified */ $_order->getBaseToGlobalRate() ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getBaseCurrencyCode() != $_order->getOrderCurrencyCode()): ?>
                    <tr>
                        <th>
                        <?= /** @escapeNotVerified */  __(
                            '%1 / %2 rate:',
                            $_order->getOrderCurrencyCode(),
                            $_order->getBaseCurrencyCode()
                        ) ?>
                        </th>
                        <th><?= /** @escapeNotVerified */ $_order->getBaseToOrderRate() ?></th>
                    </tr>
                <?php endif; ?>
            </table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information">
            <?php /** Account Information */?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Account Information')) ?></span>
                <div class="actions"><?= /** @escapeNotVerified */ $block->getAccountEditLink()?></div>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tr>
                        <th><?= $block->escapeHtml(__('Customer Name')) ?></th>
                        <td>
                            <?php if ($_customerUrl = $block->getCustomerViewUrl()): ?>
                                <a href="<?= /** @escapeNotVerified */ $_customerUrl ?>" target="_blank">
                                    <span><?= $block->escapeHtml($_order->getCustomerName()) ?></span>
                                </a>
                            <?php else: ?>
                                <?= $block->escapeHtml($_order->getCustomerName()) ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Email')) ?></th>
                        <td><a href="mailto:<?= $block->escapeHtml($_order->getCustomerEmail()) ?>">
                        <?= $block->escapeHtml($_order->getCustomerEmail()) ?></a>
                        </td>
                    </tr>
                    <?php if ($_groupName = $block->getCustomerGroupName()): ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Customer Group')) ?></th>
                            <td><?= /** @escapeNotVerified */ $_groupName ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php foreach ($block->getCustomerAccountData() as $data): ?>
                        <tr>
                            <th><?= /** @escapeNotVerified */ $data['label'] ?></th>
                            <td><?= /** @escapeNotVerified */ $data['value'] ?></td>
                        </tr>
                    <?php endforeach; ?>
                    <?php $orderHelper = $customRegistrationViewModel->getCustomOrderHelper();?>
                    <?php $_customerData = $orderHelper->getCurrentCustomer($_order->getCustomerId())->toArray(); ?>
                    <?php $websiteId = $_customerData['website_id'] ?? 0; ?>
                    <?php $attributeCollection = $orderHelper->attributeCollectionFilter($websiteId);?>
                    <?php $dependableFields=[];?>
                    <?php if (!empty($attributeCollection)): ?>
                        <?php foreach ($attributeCollection as $attributeData): ?>
                            <?php $attrAsArray = $attributeData->toArray(); ?>
                            <?php $_fieldValue = ''; ?>
                            <?php $optionLabel = []; ?>
                            <?php foreach ($_customerData as $key => $value) { ?>
                                <?php if ($attrAsArray['attribute_code'] == $key) { ?>
                                    <?php if ($attrAsArray['frontend_input'] == 'date') { ?>
                                        <?php if ($value) { ?>
                                            <?php $_fieldValue = date('m/d/Y', strtotime($value)); ?>
                                            <?php } ?>
                                            <?php } elseif ($attrAsArray['frontend_input'] == 'boolean') { ?>
                                            <?php $_fieldValue = $value == 1 ? 'Yes' : 'No'; ?>
                                    <?php } elseif ($attrAsArray['frontend_input'] == 'select') { ?>
                                                <?php
                                                foreach ($attributeData->getSource()->getAllOptions() as $instance) { ?>
                                                    <?php if ($value == $instance['value']) { ?>
                                                        <?php $_fieldValue = $instance['label']; ?>
                                                <?php } ?>
                                                <?php } ?>
                                                <?php } elseif ($attrAsArray['frontend_input'] == 'multiselect') { ?>
                                                    <?php
                                                    $attrSource = $attributeData->getSource();
                                                    foreach ($attrSource->getAllOptions() as $instance) { ?>
                                                        <?php if (is_array($value)) { ?>
                                                            <?php $value = $value; ?>
                                                <?php } elseif (is_string($value)) { ?>
                                                            <?php $value = explode(',', $value); ?>
                                                    <?php } ?>
                                                        <?php if (in_array($instance['value'], $value)) { ?>
                                                            <?php $optionLabel[] = $instance['label']; ?>
                                                        <?php } ?>
                                                        <?php } ?>
                                                        <?php $_fieldValue = implode(',', $optionLabel); ?>
                                                        <?php } elseif ($attrAsArray['frontend_input'] == 'image') { ?>
                                                            <?php $_fieldValue = "<img class='wk_images' width='75' 
                                                            height='75' alt='image'
                                            src='".$orderHelper->encodeFileName($attrAsArray['frontend_input'], $value)
                                                            ."'/>"; ?>
                                    <?php } elseif ($attrAsArray['frontend_input'] == 'file') { ?>
                                                            <?php $_fieldValue = "<a class='wk_images' alt='file' 
                                                            target='_blank'
                                            href='".$orderHelper->encodeFileName($attrAsArray['frontend_input'], $value)
                                                            ."'>".__('Download')."</a>"; ?>
                                    <?php } else { ?>
                                        <?php $_fieldValue = $block->escapeHtml($value); ?>
                                    <?php } ?>
                                <?php } ?>
                            <?php } ?>
                            <?php if ($_fieldValue != '' && $orderHelper->isShowInOrder($attributeData->getId())): ?>
                                
                                <?php #Dependable Fields ?>
                                <?php if (strpos($attributeData->getFrontendClass(), 'dependable_field')!== false): ?>
                                    <?php $attrCode = $attrAsArray['attribute_code'];?>
                                    <?php $dependableFields[$attrCode] = $_customerData[$attrCode];?>
                                <?php endif ?>
                                    
                                <?php #Dependable Children ?>
                                <?php if (strpos($attributeData->getFrontendClass(), 'dependable_child')!== false): ?>
                                    <?php $childClass =  $attributeData->getFrontendClass();?>
                                    <?php $childClass = explode('_', $childClass);?>
                                    <?php $parentOption = array_pop($childClass);?>
                                    <?php $parent = array_pop($childClass);?>
                                    <?php if (!isset($dependableFields[$parent])): continue ?>
                                    <?php elseif ($dependableFields[$parent]!==$parentOption): continue ?>
                                    <?php endif ?>
                                <?php endif ?>
                                <tr>
                                    <th><?= $block->escapeHtml($attributeData->getStoreLabel()) ?></th>
                                    <td><?= /** @escapeNotVerified */ $_fieldValue ?></td>
                                </tr>
                                <?php endif ?>
                                <?php endforeach; ?>
                                <?php endif; ?>
                            </table>
                        </div>
                    </div>
                </div>
            </section>
            
            <section class="admin__page-section order-addresses">
                <div class="admin__page-section-title">
                    <span class="title"><?= $block->escapeHtml(__('Address Information')) ?></span>
                </div>
                <div class="admin__page-section-content">
                    <div class="admin__page-section-item order-billing-address">
            <?php /** Billing Address */?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Billing Address')) ?></span>
                <div class="actions">
                    <?= /** @escapeNotVerified */ $block->getAddressEditLink($_order->getBillingAddress()); ?>
                </div>
            </div>
            <address class="admin__page-section-item-content">
                <?= /** @escapeNotVerified */ $block->getFormattedAddress($_order->getBillingAddress()); ?>
            </address>
        </div>
        <?php if (!$block->getOrder()->getIsVirtual()): ?>
            <div class="admin__page-section-item order-shipping-address">
                <?php /** Shipping Address */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title"><?= $block->escapeHtml(__('Shipping Address')) ?></span>
                    <div class="actions">
                        <?= /** @escapeNotVerified */ $block->getAddressEditLink($_order->getShippingAddress()); ?>
                    </div>
                </div>
                <address class="admin__page-section-item-content">
                    <?= /** @escapeNotVerified */ $block->getFormattedAddress($_order->getShippingAddress()); ?>
                </address>
            </div>
        <?php endif; ?>
    </div>
</section>
